[package]
name = "fip"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
config = "0.11.0"
serde = { version = "1.0", features = ["derive"] }
dotenv = "0.15.0"
tokio = { version = "1.38.0",features = ["full"]}
